trigger:
- main

pool: default

stages:
- stage: Create txt Files
  jobs:
  - job: CreateFiles
    steps:
    - script: bash create_files.sh

- stage: Print Hello World
  jobs:
  - job: PrintHelloWorld
    steps:
    - script: bash hello_world.sh