trigger:
- master

pool: default

stages:
- stage: Create_txt_Files
  jobs:
  - job: CreateFiles
    steps:
    - script: bash create_files.sh

- stage: Print_Hello_World
  jobs:
  - job: PrintHelloWorld
    steps:
    - script: bash hello_world.sh